USE MASTER
GO

CREATE DATABASE QUANLYNV
GO

USE QUANLYNV
GO

CREATE TABLE GIOITINH
(
	MAGT VARCHAR(20),
	TENGT NVARCHAR(50),
	CONSTRAINT PK_GIOITINH_MAGT PRIMARY KEY(MAGT)
)
GO

CREATE TABLE VAITRO
(
	MAVT VARCHAR(20),
	TENVT NVARCHAR(100),
	CONSTRAINT PK_VAITRO_MAVT PRIMARY KEY(MAVT)
)
GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	TENNV NVARCHAR(100),
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	LUONG VARBINARY(MAX),
	MAGT VARCHAR(20),
	MAVT VARCHAR(20),
	MAPB VARCHAR(20),
	MANQL VARCHAR(20),
	TENDN VARCHAR(100),
	MATKHAU VARBINARY(MAX),
	CONSTRAINT PK_NHANVIEN_MANV PRIMARY KEY(MANV),
	CONSTRAINT FK_NHANVIEN_MAGT FOREIGN KEY(MAGT) REFERENCES GIOITINH(MAGT),
	CONSTRAINT FK_NHANVIEN_MAVT FOREIGN KEY(MAVT) REFERENCES VAITRO(MAVT),
	CONSTRAINT FK_NHANVIEN_MANQL FOREIGN KEY(MANQL) REFERENCES NHANVIEN(MANV)
)
GO

CREATE TABLE PHONGBAN
(
	MAPB VARCHAR(20),
	TENPB NVARCHAR(100),
	MATRGPHG VARCHAR(20),
	CONSTRAINT PK_PHONGBAN_MAPB PRIMARY KEY(MAPB),
	CONSTRAINT FK_PHONGBAN_MATRGPHG FOREIGN KEY(MATRGPHG) REFERENCES NHANVIEN(MANV)
)
GO

ALTER TABLE NHANVIEN ADD
	CONSTRAINT FK_NHANVIEN_MAPB FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB)
GO

CREATE TABLE DEAN
(
	MADA VARCHAR(20),
	TENDA NVARCHAR(100),
	NGAYBD DATETIME,
	MAPB VARCHAR(20),
	CONSTRAINT PK_DEAN_MADA PRIMARY KEY(MADA),
	CONSTRAINT FK_DEAN_MAPB FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB)
)
GO

CREATE TABLE PHANCONG
(
	MADA VARCHAR(20),
	MANV VARCHAR(20),
	THOIGIAN FLOAT,
	CONSTRAINT PK_PHANCONG PRIMARY KEY(MADA, MANV)
)
GO

INSERT INTO GIOITINH(MAGT, TENGT) VALUES
	('GT01', N'Nam'),
	('GT02', N'Nữ'),
	('GT03', N'Bí mật')
GO

INSERT INTO VAITRO(MAVT, TENVT) VALUES
	('VT01', N'DBA')
GO

INSERT INTO NHANVIEN(MANV, TENNV, NGAYSINH, DIACHI, MAGT, MAVT, TENDN, MATKHAU) VALUES
	('NV01', N'Huỳnh Nhật Anh', '2003-06-04', N'123 An Dương Vương P.4 Q.5', 'GT01', 'VT01', 'anhhn', CONVERT(VARBINARY(MAX), HASHBYTES('MD5', '123456')))
GO

SELECT * FROM NHANVIEN
GO

SELECT * FROM GIOITINH
GO

CREATE PROCEDURE SP_LOGIN_NHANVIEN
(
	@USERNAME VARCHAR(100),
	@PASSWORD VARBINARY(MAX),
	@ROLE NVARCHAR(100),
	@LOGINSTATUS NVARCHAR(20) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @ROLEID VARCHAR(20)
	SELECT @ROLEID = MAVT FROM VAITRO WHERE TENVT = @ROLE

	IF EXISTS(SELECT 1 FROM NHANVIEN WHERE TENDN = @USERNAME AND MATKHAU = @PASSWORD AND MAVT = @ROLEID)
	BEGIN
		SET @LOGINSTATUS = 'SUCCESS';
	END
	ELSE
	BEGIN
		SET @LOGINSTATUS = 'FAILED';
	END
END
GO

DECLARE @PASSWORDHASH VARBINARY(MAX)
DECLARE @RESULT NVARCHAR(20)
SET @PASSWORDHASH = HASHBYTES('MD5', '123456')
EXEC SP_LOGIN_NHANVIEN N'anhhn', @PASSWORDHASH, N'DBA', @RESULT OUTPUT
PRINT @RESULT
