USE MASTER
GO

CREATE DATABASE QUANLYNV
GO

USE QUANLYNV
GO

CREATE TABLE TRANGTHAI
(
	MATT VARCHAR(20),
	TENTT NVARCHAR(100),
	CONSTRAINT PK_TRANGTHAI_MATT PRIMARY KEY(MATT)
)
GO

CREATE TABLE GIOITINH
(
	MAGT VARCHAR(20),
	TENGT NVARCHAR(50),
	CONSTRAINT PK_GIOITINH_MAGT PRIMARY KEY(MAGT)
)
GO

CREATE TABLE VAITRO
(
	MAVT VARCHAR(20),
	TENVT NVARCHAR(100),
	CONSTRAINT PK_VAITRO_MAVT PRIMARY KEY(MAVT)
)
GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	TENNV NVARCHAR(100),
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	LUONG VARBINARY(MAX),
	MAGT VARCHAR(20),
	MAVT VARCHAR(20),
	MAPB VARCHAR(20),
	MANQL VARCHAR(20),
	MATT VARCHAR(20),
	TENDN VARCHAR(100),
	MATKHAU VARBINARY(MAX),
	NGAYTAO DATETIME,
	CONSTRAINT PK_NHANVIEN_MANV PRIMARY KEY(MANV),
	CONSTRAINT FK_NHANVIEN_MAGT FOREIGN KEY(MAGT) REFERENCES GIOITINH(MAGT),
	CONSTRAINT FK_NHANVIEN_MAVT FOREIGN KEY(MAVT) REFERENCES VAITRO(MAVT),
	CONSTRAINT FK_NHANVIEN_MANQL FOREIGN KEY(MANQL) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_NHANVIEN_MATT FOREIGN KEY(MATT) REFERENCES TRANGTHAI(MATT)
)
GO

CREATE TABLE PHONGBAN
(
	MAPB VARCHAR(20),
	TENPB NVARCHAR(100),
	MATRGPHG VARCHAR(20),
	CONSTRAINT PK_PHONGBAN_MAPB PRIMARY KEY(MAPB),
	CONSTRAINT FK_PHONGBAN_MATRGPHG FOREIGN KEY(MATRGPHG) REFERENCES NHANVIEN(MANV)
)
GO

ALTER TABLE NHANVIEN ADD
	CONSTRAINT FK_NHANVIEN_MAPB FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB)
GO

CREATE TABLE DEAN
(
	MADA VARCHAR(20),
	TENDA NVARCHAR(100),
	NGAYBD DATETIME,
	MAPB VARCHAR(20),
	CONSTRAINT PK_DEAN_MADA PRIMARY KEY(MADA),
	CONSTRAINT FK_DEAN_MAPB FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB)
)
GO

CREATE TABLE PHANCONG
(
	MADA VARCHAR(20),
	MANV VARCHAR(20),
	THOIGIAN FLOAT,
	CONSTRAINT PK_PHANCONG PRIMARY KEY(MADA, MANV),
	CONSTRAINT FK_PHANCONG_MADA FOREIGN KEY(MADA) REFERENCES DEAN(MADA),
	CONSTRAINT FK_PHANCONG_MANV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)
GO

INSERT INTO GIOITINH(MAGT, TENGT) VALUES
	('GT01', N'Nam'),
	('GT02', N'Nữ'),
	('GT03', N'Bí mật')
GO

INSERT INTO VAITRO(MAVT, TENVT) VALUES
	('VT01', N'DBA'),
	('VT02', N'Trưởng phòng')
GO

INSERT INTO TRANGTHAI(MATT, TENTT) VALUES
	('TT01', N'Đang mở khóa'),
	('TT02', N'Đang khóa')

INSERT INTO NHANVIEN(MANV, TENNV, NGAYSINH, DIACHI, MAGT, MAVT, MATT, TENDN, MATKHAU, NGAYTAO) VALUES
	('NV01', N'Huỳnh Nhật Anh', '2003-06-04', N'123 An Dương Vương P.4 Q.5', 'GT01', 'VT01', 'TT01', 'anhhn', CONVERT(VARBINARY(MAX), HASHBYTES('MD5', '123456')), GETDATE())
GO

SELECT * FROM NHANVIEN
GO

SELECT * FROM GIOITINH
GO

CREATE PROCEDURE SP_LOGIN_NHANVIEN
(
    @USERNAME VARCHAR(100),
    @PASSWORD VARBINARY(MAX),
    @ROLEID VARCHAR(20),
    @LOGINSTATUS INT OUTPUT --0: TÀI KHOẢN KO TRÙNG KHỚP, 1: TÀI KHOẢN TRÙNG KHỚP VÀ TÀI KHOẢN ĐANG MỞ KHÓA, 2: TÀI KHOẢN TRÙNG KHỚP VÀ TÀI KHOẢN ĐANG KO MỞ KHÓA
)
AS
BEGIN
    SET NOCOUNT ON;

    IF (EXISTS (SELECT 1
        FROM NHANVIEN NV
        WHERE TENDN COLLATE Latin1_General_CS_AS = @USERNAME COLLATE Latin1_General_CS_AS AND MATKHAU = @PASSWORD AND MAVT = @ROLEID))
    BEGIN
		DECLARE @STATUS NVARCHAR(100)
        -- Lấy trạng thái tài khoản từ bảng TRANGTHAI
        SELECT @STATUS = TT.TENTT
        FROM TRANGTHAI TT
        INNER JOIN NHANVIEN NV ON NV.MATT = TT.MATT
        WHERE NV.TENDN COLLATE Latin1_General_CS_AS = @USERNAME COLLATE Latin1_General_CS_AS AND NV.MATKHAU = @PASSWORD AND NV.MAVT = @ROLEID;

        -- Kiểm tra trạng thái của tài khoản và thiết lập giá trị cho biến @LOGINSTATUS
        IF (@STATUS = N'Đang mở khóa')
        BEGIN
            SET @LOGINSTATUS = 1; -- Tài khoản trùng khớp và mở khóa
        END
        ELSE
        BEGIN
            SET @LOGINSTATUS = 2; -- Tài khoản trùng khớp nhưng không mở khóa
        END
    END
    ELSE
    BEGIN
        SET @LOGINSTATUS = 0; -- Tài khoản không trùng khớp
    END
END
GO


DECLARE @PASSWORDHASH VARBINARY(MAX)
DECLARE @RESULT INT
SET @PASSWORDHASH = HASHBYTES('MD5', '123456')
EXEC SP_LOGIN_NHANVIEN 'anhHn', @PASSWORDHASH, 'VT01', @RESULT OUTPUT
PRINT @RESULT

UPDATE NHANVIEN SET MATT='TT01' WHERE MANV='NV01'

